StylesPath = .github/styles
MinAlertLevel = warning

Packages = ./vendor/Millennialism.zip

[*.{md,markdown,mdx,adoc,txt,rst,html}]
BasedOnStyles = Vale, Millennialism
Vocab = Base, MillennialismExceptions

# Optional:
# Millennialism.OptionalBroadTerms = YES
